### ISSUE TITLE
No calculation for precipitation values (Rain_Counter) on HmIP-SWO-PR

### ISSUE THREAD

**Issue by CaneTLOTW** [foxthefox/ioBroker.statistics#42]
Hi,

I'm trying to calculate sumDelta for precipitation measurements of a Homematic HmIP-SWO-PR.
It is working fine for the the sunshine information, but not at all for precipitation (Rain_Counter).
However, settings are the same for both objects.

![grafik](https://user-images.githubusercontent.com/35076818/78338717-8fb70500-7593-11ea-8b1e-b3029368962f.png)

![grafik](https://user-images.githubusercontent.com/35076818/78338515-3b138a00-7593-11ea-90d3-eeadda44831d.png)

![grafik](https://user-images.githubusercontent.com/35076818/78338543-46ff4c00-7593-11ea-9c62-9d59e249a794.png)

![grafik](https://user-images.githubusercontent.com/35076818/78338936-f50af600-7593-11ea-9701-b70ef3b566ba.png)

![grafik](https://user-images.githubusercontent.com/35076818/78338440-1ae3cb00-7593-11ea-92dc-e4aaad705248.png)

![grafik](https://user-images.githubusercontent.com/35076818/78338806-bb39ef80-7593-11ea-8e08-ed651ea9fa9f.png)

It is also raining for a while now and the rain counter value is increasing.

Any ideas?

BR

**Comment by foxthefox** [comment]
maybe there is something with the value as real or integer, but I dont think that this is the case hence both are numbers in iobroker
Can you check the debug if the received values for rain is recognized from the adapter.
There must be a message:
[STATE CHANGE] ======================= "RAIN-ID" ======================='
[STATE CHANGE] stateChange =>  "VALUE"  "TRUE/FALSE"

if at the end of the second line is "false" then the adapter will not catch it, because of type "command" and not "status". The adapter is only checking status changes.

**Comment by CaneTLOTW** [comment]
Hi,
for some reason it started to work after a while.
Maybe after a complete restart of ioBroker.... Cannot fully reconstruct the condictions.
